title: 
  Cameron   <br>
  De La Pena # your name (or website title) here
logo: "images/oooo.plus_197.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst, aspiring Data Scientist, programming enthusiast. <br>
  MS in Business Analytics
  <br><br>
  <a href="https://www.linkedin.com/in/camerondelapena/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-160970981-1 # your Google Analytics tracking ID here
